name: CI-CD
on: [push]
env:
  prod-dist: 'product-distribution'
jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        # TODO: enable os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
      - name: Setup Nodejs 16.x then Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Build product
        run: |
          yarn --frozen-lockfile
          yarn build-pub
          yarn bdd-test